In [4]:
import numpy as np


In [5]:
A=np.array([[[1,2,3],[1,2,3],[1,2,3]]])


In [23]:
A

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
B=np.array([[1,2,3],[45,"rai",6]])

In [25]:
B

array([['1', '2', '3'],
       ['45', 'rai', '6']], dtype='<U11')

In [20]:
B.dtype

dtype('<U11')

In [21]:
# int==> float ==> complex ==> str

In [22]:
A.ndim


1

In [27]:
B.ndim

2

In [31]:
len(B)

2

In [32]:
B.size

6

In [33]:
type(B)

numpy.ndarray

In [34]:
B.shape

(2, 3)

In [35]:
A.shape

(9,)

In [36]:
A.data

# How to create array using built-in numpy functions

In [6]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
np.arange(1,20,-1)

array([], dtype=int32)

In [11]:
np.arange(20,0,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
S=np.eye(4,5)
S

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [28]:
v=np.identity(4)
v

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
v.diagonal()

array([1., 1., 1., 1.])

In [32]:
S.diagonal()

array([1., 1., 1., 1.])

In [33]:
v[0]

array([1., 0., 0., 0.])

In [67]:
T=np.array([[[1,2,3],[45,5,6],[4,7,6]]])
T

array([[[ 1,  2,  3],
        [45,  5,  6],
        [ 4,  7,  6]]])

In [68]:
T.ndim

3

In [69]:
T.shape

(1, 3, 3)

In [70]:
T.size

9

In [71]:
T[0][1]

array([45,  5,  6])

In [74]:
T[0][0][1]=10

In [75]:
T

array([[[ 1, 10,  3],
        [45,  5,  6],
        [ 4,  7,  6]]])

In [94]:
np.arange(20,0,-2)[::-2]

array([ 2,  6, 10, 14, 18])