In [1]:
import numpy as np

In [2]:
A=np.array([[1,2],[3,4]])

In [18]:
A

array([[1, 2],
       [3, 4]])

In [3]:
A.ndim

2

In [4]:
A.shape

(2, 2)

In [6]:
A.size

4

In [23]:
A

array([[1, 2],
       [3, 4]])

In [22]:
A.itemsize

4

In [7]:
A.dtype.name

'int32'

In [10]:
B=np.array([[1,2,5],[3,6,4,],[1,4,5]])

In [11]:
B


array([[1, 2, 5],
       [3, 6, 4],
       [1, 4, 5]])

In [12]:
B.ndim

2

In [13]:
B.shape


(3, 3)

In [14]:
B.dtype.name

'int32'

In [16]:
C=([[11,10],[5,6]])

In [17]:
A+C

array([[12, 12],
       [ 8, 10]])

In [19]:
A**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [20]:
A*A

array([[ 1,  4],
       [ 9, 16]])

In [21]:
np.dot(A,A)

array([[ 7, 10],
       [15, 22]])

In [24]:
a[1:]

NameError: name 'a' is not defined

In [25]:
A[1:]

array([[3, 4]])

In [26]:
A[0:]

array([[1, 2],
       [3, 4]])

In [27]:
B[1:]

array([[3, 6, 4],
       [1, 4, 5]])

In [28]:
B[:1]

array([[1, 2, 5]])

In [29]:
B[:3]

array([[1, 2, 5],
       [3, 6, 4],
       [1, 4, 5]])

In [30]:
B[:0]

array([], shape=(0, 3), dtype=int32)

In [31]:
B[:1]

array([[1, 2, 5]])

In [32]:
B[1:]

array([[3, 6, 4],
       [1, 4, 5]])

In [33]:
B[2:]

array([[1, 4, 5]])

In [34]:
B[0:]

array([[1, 2, 5],
       [3, 6, 4],
       [1, 4, 5]])

In [35]:
B[:2]

array([[1, 2, 5],
       [3, 6, 4]])

In [36]:
B[0:1]

array([[1, 2, 5]])

In [41]:
B[1,2]

4

In [42]:
B[0,0:3]

array([1, 2, 5])

In [44]:
B[:, 1]

array([2, 6, 4])

In [45]:
B[:, 0]

array([1, 3, 1])

In [46]:
B[0]

array([1, 2, 5])

In [47]:
B[:3]

array([[1, 2, 5],
       [3, 6, 4],
       [1, 4, 5]])

In [48]:
B[:,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [49]:
B[:,2]

array([5, 4, 5])

In [50]:
A.ravel()

array([1, 2, 3, 4])

In [51]:
B.ravel()

array([1, 2, 5, 3, 6, 4, 1, 4, 5])

In [52]:
A.shape=(1,4)

In [53]:
A

array([[1, 2, 3, 4]])

In [54]:
B.shape=(3,4)

ValueError: cannot reshape array of size 9 into shape (3,4)

In [55]:
A.transpose()

array([[1],
       [2],
       [3],
       [4]])

In [56]:
A

array([[1, 2, 3, 4]])

In [57]:
B.transpose()

array([[1, 3, 1],
       [2, 6, 4],
       [5, 4, 5]])

# Sum of all elements in A

In [60]:
sum=0
for i in A.ravel():
    sum=sum+i
print(sum)

10


In [61]:
A.shape=(2,2)

In [62]:
A

array([[1, 2],
       [3, 4]])

In [63]:
B.shape=(3,3)

In [64]:
B

array([[1, 2, 5],
       [3, 6, 4],
       [1, 4, 5]])

In [65]:
sum=0
for i in A.ravel():
    sum=sum+i
print(sum)

10


In [ ]:
# sum of first row
sum=0
for i in B[0]:
    sum=sum+i
print(sum)

In [72]:
#sum of first column
sum=0
for i in B[:,0]:
    sum=sum+i
print(sum)

5


In [70]:
B

array([[1, 2, 5],
       [3, 6, 4],
       [1, 4, 5]])

In [74]:
dot=1
for i in B[:,0]:
    dot=dot*i
print(dot)

3


In [80]:
dot=1
for i in B[:2]:
    dot=dot*i
print("C=",dot)


C= [ 3 12 20]


In [75]:
B[:2]

array([[1, 2, 5],
       [3, 6, 4]])

In [81]:
product=1
for i in B.ravel():
    product=product*i
print(product)

14400


In [83]:
product=1
for i in B[:,0]:
    product=product*i
print(product)

3
