In [1]:
import numpy as np

In [2]:
a=np.arange(1,25).reshape(4,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [3]:
a.shape

(4, 6)

In [5]:
a.size

24

In [8]:
a.reshape(6,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [9]:
a.reshape(-1,24)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [10]:
a.reshape(1,24)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [11]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

# Conditional Statement 

In [ ]:
#select the no greater than 10

In [13]:

a>10#===> bool output

array([[False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [14]:
a[a<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a[np.array(a<10)]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

# np.where

In [26]:
#where(condition, [x, y])
#Return elements chosen from `x` or `y` depending on `condition`.
b=np.where(a<10,a,-a)
b

array([[  1,   2,   3,   4,   5,   6],
       [  7,   8,   9, -10, -11, -12],
       [-13, -14, -15, -16, -17, -18],
       [-19, -20, -21, -22, -23, -24]])

In [23]:
a[[False,True,False,True]]# it returns 2 and 4  column

array([[ 7,  8,  9, 10, 11, 12],
       [19, 20, 21, 22, 23, 24]])

In [24]:
a


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [28]:
salary=np.array([10,15,87,63,21,24,27])# salarly in k

In [30]:
np.where(salary<30,salary+1,salary)*1000
#where salary is <30 give 1k bonus
#where salary is not <30 keep as it is

array([11000, 16000, 87000, 63000, 22000, 25000, 28000])

In [35]:
salary[salary%2==0]

array([10, 24])

# Scalar Math

In [37]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [38]:
# add 10 to each element
a+10# temp change

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34]])

In [39]:
a*10

array([[ 10,  20,  30,  40,  50,  60],
       [ 70,  80,  90, 100, 110, 120],
       [130, 140, 150, 160, 170, 180],
       [190, 200, 210, 220, 230, 240]])

In [40]:
a/2

array([[ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5,  5. ,  5.5,  6. ],
       [ 6.5,  7. ,  7.5,  8. ,  8.5,  9. ],
       [ 9.5, 10. , 10.5, 11. , 11.5, 12. ]])

In [41]:
a+=10# inplace change

In [42]:
a

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34]])

In [43]:
b=np.arange(1,7)
b

array([1, 2, 3, 4, 5, 6])

In [46]:
b.shape=(2,3)
b


array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
b**=2
b

array([[ 1,  4,  9],
       [16, 25, 36]])

# vector math

In [50]:
a=np.array([[1,2],[3,4]])
a


array([[1, 2],
       [3, 4]])

In [52]:
b=np.array([[1,4],[5,8]])
b

array([[1, 4],
       [5, 8]])

In [58]:
# element wise add sub, mupltiplication,division
a+b




array([[ 2,  6],
       [ 8, 12]])

In [55]:
a-b

array([[ 0, -2],
       [-2, -4]])

In [56]:
a*b

array([[ 1,  8],
       [15, 32]])

In [57]:
a/b

array([[1. , 0.5],
       [0.6, 0.5]])

In [60]:
a & b

array([[1, 0],
       [1, 0]], dtype=int32)

In [62]:
12 & 40

8

In [63]:
12 and 40#x and  y==> if x is True then return y

40

In [64]:
0 &40 #x and  y==> if x is False then return False

0

In [65]:
np.add(a,b)

array([[ 2,  6],
       [ 8, 12]])

In [69]:
np.subtract(a,b)


array([[ 0, -2],
       [-2, -4]])

In [66]:
np.divide(a,b)

array([[1. , 0.5],
       [0.6, 0.5]])

In [67]:
np.multiply(a,b)

array([[ 1,  8],
       [15, 32]])

In [68]:
np.power(a,2)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [70]:
#negation
~a

array([[-2, -3],
       [-4, -5]], dtype=int32)

In [71]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [72]:
np.add(a,1)

array([[2, 3],
       [4, 5]])

In [73]:
np.log(a)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

# How to delete element

In [85]:
a=np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [77]:
np.delete(a,0,axis=1)

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [86]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [89]:
np.delete(a,2,axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [83]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [79]:
a=a.ravel()

In [80]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [81]:
np.delete(a,2)

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [82]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

# Splitting the arrays

In [90]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [92]:
a[2:4]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [106]:
np.split(a,2,axis=0)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [100]:
np.split(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [101]:
np.split(a,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [110]:
np.split(a,2,axis=0)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [111]:
np.split(a,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [ ]:
np.split

In [109]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [107]:
np.vsplit(a,2)#rowwise

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [108]:
np.hsplit(a,2)#columnwise

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]